### ISSUE TITLE
Difference to incron?

### ISSUE THREAD

**Issue by xduino11** [pkittenis/cronify#3]
I just stumbled upon this repo - I've been using incron since a few years and am now reconfing some servers. Are there any specific pros to this one, or just NIH? ;-)

**Comment by pkittenis** [comment]
Hi there, thanks for the interest. 

There are many actually :) Had looked at incron before writing this and it was lacking several features that were needed. Specifically:

* Multiple actions from one event to be run in sequence
* Filename wild card matching, not just static file or all files in a dir
* Async file notifiers
* Multiple file masks within a configured watched dir, eg match on `file_like_this_*` and `file_like_that_*`, not all files
* Watch directory recursion
* Scheduled actions within time window - deferred actions
* More than just file name, path and event flags as command variables. Cronify in addition supports timezone translated file date stamp as a command variable
* File date/time stamp timezone translation to allow for action scheduling on a different timezone than the server's configured one and/or for action scheduling of files created by a client on a different timezone than the server's. For example a client in Europe sends a file to a server in US which has an event configured for it. The file's time stamp will need translating to display and be actioned - actions can have time widows and file datestamp as variable - correctly on the US timezone server.
* Thread pool with configurable size for actions to be queued with, shared with all watchers - can bring down the system by triggering thousands of action child processes without this
